import { ProDescriptionsProps } from '@ant-design/pro-descriptions';
import { RequestData } from '@ant-design/pro-descriptions/lib/useFetchData';
import { ActionType } from '@ant-design/pro-table';
import { CommonRecord } from '../types/common';
import { DeleteServiceConfig, RetrieveOneServiceConfig, UpdateServiceConfig } from './useCRUDRequests';
export declare type DescriptionsUpdateRequest = (values: CommonRecord, action?: ActionType) => Promise<boolean>;
export declare function useDescriptionsUpdateRequest(serviceConfig: UpdateServiceConfig, action?: ActionType): DescriptionsUpdateRequest;
export declare type DescriptionsDeleteRequest = () => Promise<boolean>;
export declare function useDescriptionsDeleteRequest(serviceConfig: DeleteServiceConfig): DescriptionsDeleteRequest;
export declare type DescriptionsRetrieveServiceConfig = RetrieveOneServiceConfig<RequestData>;
export declare type DescriptionsRetrieveRequest = ProDescriptionsProps['request'];
export declare function useDescriptionsRetrieveRequest(serviceConfig: DescriptionsRetrieveServiceConfig): DescriptionsRetrieveRequest;
